In [5]:
#성공트
import pandas as pd
import plotly.express as px
import mysql.connector
import pandas as pd

# MySQL 연결 설정
connection = mysql.connector.connect(host="localhost", user="root", password="tiger", database="db_test")

###월요일
# 날짜 목록
dates = [
    '2023-06-05', '2023-06-12', '2023-06-19', '2023-06-26', '2023-07-03',
    '2023-07-10', '2023-07-17', '2023-07-24', '2023-07-31', '2023-08-07',
    '2023-08-14', '2023-08-21', '2023-08-28'
]

# SQL 쿼리 생성
query = """
SELECT *
FROM cctv_events
WHERE STR_TO_DATE(event_time, '%%Y-%%m-%%d') IN ({})
""".format(', '.join(['%s'] * len(dates)))

# SQL 쿼리 실행
cursor = connection.cursor()
cursor.execute(query, dates)

# 결과 가져오기
result = cursor.fetchall()
print(result)

# 결과를 DataFrame으로 변환
df = pd.DataFrame(result, columns=["cctv_id", "event_time", "event_type", "event_item", "event_description"])
print(df)
# 'event_time' 열을 datetime 형식으로 변환
df['event_time'] = pd.to_datetime(df['event_time'])

# 'event_time' 열을 기준으로 DataFrame 정렬
df1 = df.sort_values(by='event_time')
count1 = (df['event_description'] == 'NaN').sum()
print(df1, count1)

###화요일
# 날짜 목록
dates = [
    '2023-06-06', '2023-06-13', '2023-06-20', '2023-06-27', '2023-07-04', 
    '2023-07-11', '2023-07-18', '2023-07-25', '2023-08-01', '2023-08-08', 
    '2023-08-15', '2023-08-22', '2023-08-29'
]

# SQL 쿼리 생성
query = """
SELECT *
FROM cctv_events
WHERE STR_TO_DATE(event_time, '%%Y-%%m-%%d') IN ({})
""".format(', '.join(['%s'] * len(dates)))

# SQL 쿼리 실행
cursor = connection.cursor()
cursor.execute(query, dates)

# 결과 가져오기
result = cursor.fetchall()

# 결과를 DataFrame으로 변환
df = pd.DataFrame(result, columns=["cctv_id", "event_time", "event_type", "event_item", "event_description"])

# 'event_time' 열을 datetime 형식으로 변환
df['event_time'] = pd.to_datetime(df['event_time'])

# 'event_time' 열을 기준으로 DataFrame 정렬
df2 = df.sort_values(by='event_time')
count2 = (df['event_description'] == 'NaN').sum()

###수요일
# 날짜 목록
dates = [
    '2023-06-07', '2023-06-14', '2023-06-21', '2023-06-28', '2023-07-05', 
    '2023-07-12', '2023-07-19', '2023-07-26', '2023-08-02', '2023-08-09', 
    '2023-08-16', '2023-08-23', '2023-08-30'
]

# SQL 쿼리 생성
query = """
SELECT *
FROM cctv_events
WHERE STR_TO_DATE(event_time, '%%Y-%%m-%%d') IN ({})
""".format(', '.join(['%s'] * len(dates)))

# SQL 쿼리 실행
cursor = connection.cursor()
cursor.execute(query, dates)

# 결과 가져오기
result = cursor.fetchall()

# 결과를 DataFrame으로 변환
df = pd.DataFrame(result, columns=["cctv_id", "event_time", "event_type", "event_item", "event_description"])

# 'event_time' 열을 datetime 형식으로 변환
df['event_time'] = pd.to_datetime(df['event_time'])

# 'event_time' 열을 기준으로 DataFrame 정렬
df3 = df.sort_values(by='event_time')
count3 = (df['event_description'] == 'NaN').sum()

###목요일
# 날짜 목록
dates = [
    '2023-06-08', '2023-06-15', '2023-06-22', '2023-06-29', '2023-07-06', 
    '2023-07-13', '2023-07-20', '2023-07-27', '2023-08-03', '2023-08-10', 
    '2023-08-17', '2023-08-24', '2023-08-31'
]

# SQL 쿼리 생성
query = """
SELECT *
FROM cctv_events
WHERE STR_TO_DATE(event_time, '%%Y-%%m-%%d') IN ({})
""".format(', '.join(['%s'] * len(dates)))

# SQL 쿼리 실행
cursor = connection.cursor()
cursor.execute(query, dates)

# 결과 가져오기
result = cursor.fetchall()

# 결과를 DataFrame으로 변환
df = pd.DataFrame(result, columns=["cctv_id", "event_time", "event_type", "event_item", "event_description"])

# 'event_time' 열을 datetime 형식으로 변환
df['event_time'] = pd.to_datetime(df['event_time'])

# 'event_time' 열을 기준으로 DataFrame 정렬
df4 = df.sort_values(by='event_time')
count4 = (df['event_description'] == 'NaN').sum()

###금요일
# 날짜 목록
dates = [
    '2023-06-09', '2023-06-16', '2023-06-23', '2023-06-30', '2023-07-07', 
    '2023-07-14', '2023-07-21', '2023-07-28', '2023-08-04', '2023-08-11', 
    '2023-08-18', '2023-08-25'
]

# SQL 쿼리 생성
query = """
SELECT *
FROM cctv_events
WHERE STR_TO_DATE(event_time, '%%Y-%%m-%%d') IN ({})
""".format(', '.join(['%s'] * len(dates)))

# SQL 쿼리 실행
cursor = connection.cursor()
cursor.execute(query, dates)

# 결과 가져오기
result = cursor.fetchall()

# 결과를 DataFrame으로 변환
df = pd.DataFrame(result, columns=["cctv_id", "event_time", "event_type", "event_item", "event_description"])

# 'event_time' 열을 datetime 형식으로 변환
df['event_time'] = pd.to_datetime(df['event_time'])

# 'event_time' 열을 기준으로 DataFrame 정렬
df5 = df.sort_values(by='event_time')
count5 = (df['event_description'] == 'NaN').sum()

###토요일
# 날짜 목록
dates = [
    '2023-06-10', '2023-06-17', '2023-06-24', '2023-07-01', '2023-07-08', '2023-07-15', 
    '2023-07-22', '2023-07-29', '2023-08-05', '2023-08-12', '2023-08-19', '2023-08-26'
]

# SQL 쿼리 생성
query = """
SELECT *
FROM cctv_events
WHERE STR_TO_DATE(event_time, '%%Y-%%m-%%d') IN ({})
""".format(', '.join(['%s'] * len(dates)))

# SQL 쿼리 실행
cursor = connection.cursor()
cursor.execute(query, dates)

# 결과 가져오기
result = cursor.fetchall()

# 결과를 DataFrame으로 변환
df = pd.DataFrame(result, columns=["cctv_id", "event_time", "event_type", "event_item", "event_description"])

# 'event_time' 열을 datetime 형식으로 변환
df['event_time'] = pd.to_datetime(df['event_time'])

# 'event_time' 열을 기준으로 DataFrame 정렬
df6 = df.sort_values(by='event_time')
count6 = (df['event_description'] == 'NaN').sum()

###일요일
# 날짜 목록
dates = [
    '2023-06-11', '2023-06-18', '2023-06-25', '2023-07-02', '2023-07-09', '2023-07-16', 
    '2023-07-23', '2023-07-30', '2023-08-06', '2023-08-13', '2023-08-20', '2023-08-27'
]

# SQL 쿼리 생성
query = """
SELECT *
FROM cctv_events
WHERE STR_TO_DATE(event_time, '%%Y-%%m-%%d') IN ({})
""".format(', '.join(['%s'] * len(dates)))

# SQL 쿼리 실행
cursor = connection.cursor()
cursor.execute(query, dates)

# 결과 가져오기
result = cursor.fetchall()

# 결과를 DataFrame으로 변환
df = pd.DataFrame(result, columns=["cctv_id", "event_time", "event_type", "event_item", "event_description"])

# 'event_time' 열을 datetime 형식으로 변환
df['event_time'] = pd.to_datetime(df['event_time'])

# 'event_time' 열을 기준으로 DataFrame 정렬
df7 = df.sort_values(by='event_time')
count7 = (df['event_description'] == 'NaN').sum()

# 연결 닫기
cursor.close()
connection.close()


#데이터프레임 생성
data = [count1, count2, count3, count4, count5, count6, count7]
df = pd.DataFrame(data)

df.columns = ['이벤트 건수']

# 행 이름을 변경할 딕셔너리 생성
new_index_mapping = {0: '월', 1: '화', 2: '수', 3: '목', 4: '금', 5: '토', 6: '일'}

# 행 이름 변경
df = df.rename(index=new_index_mapping)

# 라인 그래프 생성
fig = px.line(df, y='이벤트 건수')
fig.update_layout(width=780, height=320)
# HTML 파일로 저장
fig.write_html('line_graph.html')

[]
Empty DataFrame
Columns: [cctv_id, event_time, event_type, event_item, event_description]
Index: []
Empty DataFrame
Columns: [cctv_id, event_time, event_type, event_item, event_description]
Index: [] 0

In [6]:
#성공트
import pandas as pd
import plotly.express as px
import mysql.connector
import pandas as pd

# MySQL 연결 설정
connection = mysql.connector.connect(host="localhost", user="root", password="tiger", database="db_test")

###월요일
# 날짜 목록
dates = [
    '2023-06-05', '2023-06-12', '2023-06-19', '2023-06-26', '2023-07-03',
    '2023-07-10', '2023-07-17', '2023-07-24', '2023-07-31', '2023-08-07',
    '2023-08-14', '2023-08-21', '2023-08-28'
]

# SQL 쿼리 생성
query = """
SELECT *
FROM cctv_events
WHERE STR_TO_DATE(event_time, '%%Y-%%m-%%d') IN ({})
""".format(', '.join(['%s'] * len(dates)))

# SQL 쿼리 실행
cursor = connection.cursor()
cursor.execute(query, dates)

# 결과 가져오기
result = cursor.fetchall()
print(result)

# 결과를 DataFrame으로 변환
df = pd.DataFrame(result, columns=["cctv_id", "event_time", "event_type", "event_item", "event_description"])
print(df)
# 'event_time' 열을 datetime 형식으로 변환
df['event_time'] = pd.to_datetime(df['event_time'])

# 'event_time' 열을 기준으로 DataFrame 정렬
df1 = df.sort_values(by='event_time')
count1 = (df['event_description'] == 'NaN').sum()
print(df1, count1)

[]
Empty DataFrame
Columns: [cctv_id, event_time, event_type, event_item, event_description]
Index: []
Empty DataFrame
Columns: [cctv_id, event_time, event_type, event_item, event_description]
Index: [] 0